# Generated by Django 5.2.3 on 2025-06-23 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='puplish_date',
        ),
        migrations.AddField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 22, 11, 43, 274400)),
        ),
    ]
