# Generated by Django 5.2.3 on 2025-06-25 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_puplish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
